### ISSUE TITLE
No native audio recorder / call recording not working

### ISSUE THREAD

**Issue by heeplr** [crdroidandroid/crdroid_features#49]
I'm not sure if this is related (or if this even is the right issue tracker).

I'm using v6.8 Build date 2020-07-30 on herolte.

There doesn't seem to be a default voice recorder app installed and when I select "record call" during a a call, the logcat says:

```
08-06 11:23:43.576  3534  3534 I Codec2Client: Creating a Codec2 client to service "software"
08-06 11:23:43.577  3534  3534 I Codec2Client: Client to Codec2 service "software" created
08-06 11:23:43.656  3495  3852 W APM_AudioPolicyManager: getInputForAttr() failed opening input: sampling rate 48000, format 0x1, channel mask 0x10
08-06 11:23:43.656  3495  3852 E AudioFlinger: createRecord() getInputForAttr return error -38
08-06 11:23:43.656  3534  3534 E IAudioFlinger: createRecord returned error -38
08-06 11:23:43.657  3534  3534 E AudioRecord: createRecord_l(0): AudioFlinger could not create record track, status: -38
08-06 11:23:43.658  3534  3534 E StagefrightRecorder: audio source is not initialized
08-06 11:23:43.659 12936 12954 E MediaRecorder: start failed: -2147483648
08-06 11:23:43.696 12936 12954 W CallRecorderService: Could not start recording
08-06 11:23:43.696 12936 12954 W CallRecorderService: java.lang.RuntimeException: start failed.
08-06 11:23:43.696 12936 12954 W CallRecorderService:   at android.media.MediaRecorder.start(Native Method)
08-06 11:23:43.696 12936 12954 W CallRecorderService:   at com.android.dialer.callrecord.impl.CallRecorderService.startRecordingInternal(CallRecorderService.java:153)
08-06 11:23:43.696 12936 12954 W CallRecorderService:   at com.android.dialer.callrecord.impl.CallRecorderService.access$100(CallRecorderService.java:45)
08-06 11:23:43.696 12936 12954 W CallRecorderService:   at com.android.dialer.callrecord.impl.CallRecorderService$1.startRecording(CallRecorderService.java:62)
08-06 11:23:43.696 12936 12954 W CallRecorderService:   at com.android.dialer.callrecord.ICallRecorderService$Stub.onTransact(ICallRecorderService.java:100)
08-06 11:23:43.696 12936 12954 W CallRecorderService:   at android.os.Binder.execTransactInternal(Binder.java:1021)
08-06 11:23:43.696 12936 12954 W CallRecorderService:   at android.os.Binder.execTransact(Binder.java:994)
08-06 11:23:43.696  3534  3534 W StagefrightRecorder: stop while neither recording nor paused
08-06 11:23:43.696  3534  3534 W StagefrightRecorder: stop while neither recording nor paused
08-06 11:23:43.697  3534 13368 W StagefrightRecorder: stop while neither recording nor paused
08-06 11:23:43.750 12826 12900 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1008x231]-format:1
08-06 11:23:45.712  3503  3829 E BufferQueueProducer: [Toast#0] disconnect: not connected (req=1)
08-06 11:23:45.712 12826 12900 W libEGL  : EGLNativeWindowType 0x76ab108d50 disconnect failed
08-06 11:23:45.736  3713  5844 W NotificationService: Toast already killed. pkg=com.android.dialer callback=android.app.ITransientNotification$Stub$Proxy@57ae3f9
```

any help, hint or rant appreciated ;)

**Comment by gursewak10** [comment]
hey does it have allowed for storage permission?

**Comment by heeplr** [comment]
yes, i was asked the first time an gave permission.

**Comment by gwolf2u** [comment]
as this is really not the place to report bugs and also since this is rather device specific issue, I'll close this issue
please ask device maintainer in support forum or Telegram (see https://crdroid.net/herolte support button) to fix it if possible
